---
- hosts: "{{ variable_host | default('webservers') }}"
  vars_files:
    - vars.yaml
  become: yes
  become_method: sudo
  remote_user: '{{ user }}'

  tasks:
  - name: copy war file to web servers
    copy: 
      src: '{{ warFilePath }}'
      dest: /opt/tomcat/webapps/petclinic.war    
    
