name: SpringApp CI-CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - "main"
      - "release"
  pull_request:
    branches: 
      - "release"

jobs:
  buildApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Build with maven
        run: mvn clean package
